version: "2.4"
services:
  schema-registry:
    environment:
      SCHEMA_REGISTRY_HOST_NAME: node-1
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: node-1:9092,node-2:9092
      SCHEMA_REGISTRY_DEBUG: true
    extra_hosts:
      - "node-1:192.168.56.131"
      - "node-2:192.168.56.132"
