version: "2.4"
services:
  broker:
    container_name: kafka-broker
    user: appuser:appuser
    image: confluentinc/cp-kafka:7.5.3
    restart: "on-failure:15"
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - data:/var/lib/kafka/data:rw
volumes:
  data:
    name: kafka-data